name: AD.emmit('tech');
description: My journey as a Software Engineer
meta_description: 'This is the personal blog area of Ashok Dey who is a software engineer and is working as Fullstack JavaScript Engineer since last 2 years. His primary tech stack consists of Node.js, MySQL, MongoDB, Redis, AWS, React.js & Redux'

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://ashokdey.in/blog'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url: 'https://ashokdey.in/blog'
author: 'Ashok Dey'
